version: '3.2'

services:

  frontend:
    build: /opt/frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    volumes:
      - /opt/backend/public:/app/public
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    volumes:
      - /opt/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      DB: "${DB}"
      DB_LOGIN: "${DB_LOGIN}"
      DB_PASSWORD: "${DB_PASSWORD}"
